kind: pipeline
type: docker
name: cthunline-web-ci

# when to execute pipeline
trigger:
  branch:
  - master
  - dev
  event:
  - push
  - pull_request

steps:
# install dependencies
- name: install
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm i
  depends_on:
  - clone
# linters
- name: lint
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - install
# sonarqube scan
- name: sonarqube
  image: pitininja/drone-sonar-plugin:latest
  failure: ignore
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  depends_on:
  - install
  when:
    branch:
    - dev
    event:
    - push
