kind: pipeline
type: docker
name: cthunline-web-ci

# when to execute pipeline
trigger:
  branch:
  - master
  event:
  - push
  - pull_request

steps:
# install dependencies
- name: install
  image: node:20-alpine
  pull: if-not-exists
  commands:
  - npm i
# linters
- name: lint
  image: node:20-alpine
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - install
# sonarqube scan
- name: sonarqube
  image: plugins/sonarqube-scanner
  failure: ignore
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  depends_on:
  - install
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
type: docker
name: cthunline-cd

# when to execute pipeline
trigger:
  event:
  - tag

# disable default cloning
clone:
  disable: true

# building and publishing docker image
steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/cthunline/cthunline-docker.git .
  - apk update
  - apk add --no-cache tail cut
  - API_TAG=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags git@github.com:cthunline/cthunline-api.git '*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3 | cut --delimiter='v' --fields=2)
  - WEB_TAG=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags git@github.com:cthunline/cthunline-web.git '*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3 | cut --delimiter='v' --fields=2)
  - echo "latest,$API_TAG-$WEB_TAG"
  - echo "latest,$API_TAG-$WEB_TAG" > .tags
- name: docker  
  image: plugins/docker
  settings:
    repo: cthunline/cthunline
    username:
      from_secret: docker_user
    password:
      from_secret: docker_token
    squash: true
